---
resources:
- name: DB2-Server-Base 
  type: git
  source:
    uri: https://github.com/ahilden/concourse-tutorial.git

- name: DB2-Server-1.1.1 
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

jobs:
- name: DB2-Server-CVT 
  public: true
  plan:
  - get: DB2-Server-Base 
  - get: DB2-Server-1.1.1 
  - task: create-some-files
    file: DB2-Server-Base/11_task_outputs_to_inputs/create_some_files.yml
  - task: show-some-files
    file: DB2-Server-Base/11_task_outputs_to_inputs/show_files.yml
